# Generated by Django 3.1.7 on 2021-03-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_profile_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fullname',
            field=models.CharField(default='rahi', max_length=30),
            preserve_default=False,
        ),
    ]
