# Generated by Django 3.1.7 on 2021-03-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210322_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fullname',
            field=models.CharField(default='rahi', max_length=30),
            preserve_default=False,
        ),
    ]
